dist: bionic
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
    - DOCKER_VERSION=18.06.0~ce-0~ubuntu
  matrix:
    - TO_TEST=pfcon
    - TO_TEST=cube

before_install:
  - ./travis_before_install.sh
      
# command to install dependencies
install:
  - docker pull fnndsc/swarm
  - travis_wait docker build -t fnndsc/pfcon:dev -f Dockerfile_dev .

before_script:
  - if [ "$TO_TEST" = "pfcon" ]; then ./travis_before_script.sh; fi
  - if [ "$TO_TEST" = "cube" ]; then ./travis_cube_before_script.sh; fi
  - docker swarm init --advertise-addr 127.0.0.1

# command to run tests
script: 
  - if [ "$TO_TEST" = "pfcon" ]; then docker-compose -f docker-compose_dev.yml exec pfcon_service nosetests --exe tests; fi
  - if [ "$TO_TEST" = "cube" ]; then cd ../ChRIS_ultron_backEnd/; docker-compose -f docker-compose_dev.yml exec chris_dev python manage.py test --tag integration; fi

after_script:
  - if [ "$TO_TEST" = "pfcon" ]; then docker-compose -f docker-compose_dev.yml down; sudo rm -fr ./FS; fi
  - if [ "$TO_TEST" = "cube" ]; then cd ../ChRIS_ultron_backEnd/; docker-compose -f docker-compose_dev.yml down -v; sudo rm -fr ./FS; fi
  - docker swarm leave --force;
notifications:
  slack: fnndsc:gGPIVAOtMikWomA1EKrVYIjO
