dist: bionic
sudo: required

services:
  - docker

language: python
python: 
  - "3.8"
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
    - DOCKER_VERSION=18.06.0~ce-0~ubuntu

before_install:
  ./cube_before_install.sh;
      
before_script:
  ./cube_before_script.sh;

# command to run tests
script:
  cd ../ChRIS_ultron_backEnd/; docker-compose -f docker-compose_dev.yml exec chris_dev python manage.py test --tag integration;

after_script:
  cd ../ChRIS_ultron_backEnd/; docker-compose -f docker-compose_dev.yml down -v; sudo rm -fr ./FS; docker swarm leave --force;
notifications:
  slack: fnndsc:xcwPXeUGBBNRkwAlygS9gtCo
