language: python
services:
  - docker
matrix:
  include:
    #case 1: build pman and test integration with CUBE
    - dist: xenial
      env: To_Test=cube
      
before_script:
  - if [ "$To_Test" = "cube" ]; then mv pman/CUBE_CI.sh CUBE_CI.sh; ./CUBE_CI.sh; fi

# command to run tests
script: 
  - if [ "$To_Test" = "pman" ];then nosetests; fi
  - if [ "$To_Test" = "cube" ]; then cd ../ChRIS_ultron_backEnd/; docker-compose exec chris_dev python manage.py test --tag integration; fi

notifications:
  slack: fnndsc:xcwPXeUGBBNRkwAlygS9gtCo