# https://docs.docker.com/compose/yml/
# Each service defined in docker-compose.yml must specify exactly one of
# image or build. Other keys are optional, and are analogous to their
# docker run command-line counterparts.
#
# As with docker run, options specified in the Dockerfile (e.g., CMD,
# EXPOSE, VOLUME, ENV) are respected by default - you don't need to
# specify them again in docker-compose.yml.
#

version: '3.7'

services:
  pfcon_service:
    image: fnndsc/pfcon
    env_file:
      - ./secrets/.pfcon_service.env
    ports:
      - "5005:5005"
    depends_on:
      - pman_service
      - pfioh_service
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - remote
    labels:
      name: "pfcon"
      role: "pfcon service"

  pfioh_service:
    # We need to mount a physical dir in the HOST onto the key store in pfioh. This dir
    # is given by the STOREBASE env variable. The keystore is specified by the
    # --storeBase flag.
    image: fnndsc/pfioh
    command: ["--forever", "--httpResponse", "--createDirsAsNeeded", "--storeBase", "/hostFS/storeBase", "--verbosity", "1"]
    volumes:
      - ${STOREBASE:?}:/hostFS/storeBase
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      remote:
        aliases:
          - pfioh.remote
    labels:
      name: "pfioh"
      role: "pfioh service"

  pman_service:
    # Since pman spins off containers of its own it needs to mount storeBase dir (where
    # pfioh shares the data) into the spawned container. This directory is passed in the
    # STOREBASE env variable.
    environment:
      - STOREBASE
    image: fnndsc/pman
    env_file:
      - ./secrets/.pman_service.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      remote:
        aliases:
          - pman.remote
    labels:
      name: "pman"
      role: "pman service"

networks:
  remote:
