# run pfcon unit tests and CUBE integration tests
# pfcon's nosetests are run during docker build

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t fnndsc/pfcon .
      - uses: FNNDSC/cube-integration-action@v1
