# run pfcon unit tests (nosetests) and cube integration tests

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nose:
    name: Nose tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install deps for pycurl
        run: sudo apt-get install -qq libssl-dev libcurl4-openssl-dev
      - name: install pip dependencies
        run: |
          pip install .
          pip install nose
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: nosetests
        run: nosetests
  cube:
    name: CUBE tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t fnndsc/pfcon .
      - uses: FNNDSC/cube-integration-action@v1
  slack-notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [nose, cube]
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_USERNAME: Github Actions Bot
      SLACK_ICON: https://github.githubassets.com/images/modules/site/features/actions-icon-actions.svg
      SLACK_FOOTER: ""
    steps:
      - name: Slack Notification (passing)
        uses: rtCamp/action-slack-notify@v2
        id: passing
        if: ${{ needs.nose.result == 'success' && needs.cube.result == 'success' }}
        env:
          SLACK_COLOR: good
          SLACK_TITLE: Passing
          SLACK_MESSAGE: "Build successful :tada:"
      - name: Slack Notification (failing)
        uses: rtCamp/action-slack-notify@v2
        if: ${{ steps.passing.conclusion == 'skipped' }}
        env:
          SLACK_COLOR: bad
          SLACK_TITLE: Failing
          SLACK_MESSAGE: "Tests were unsuccessful :no_entry:"
